#!/usr/bin/env python3
"""Offline binary64 transport/conversion/arithmetic fixtures; no runtime dependency.

Python float(int) and float(Fraction) use nearest, ties-to-even on supported
CPython IEEE binary64 hosts. Exact rational values model each rounding point.
This bootstrap corpus tests core primitives, not future luna-utils algorithms.
"""
import argparse
from fractions import Fraction
import json
from pathlib import Path
import struct
import subprocess

ROOT = Path(__file__).resolve().parents[1]

def bits(value):
    return struct.unpack(">Q", struct.pack(">d", value))[0]

def generate():
    assert bits(float(2**53 + 1)) == 0x4340000000000000
    cases = []
    for name, value in [
        ("positive_zero", 0), ("negative_zero", 1 << 63),
        ("min_subnormal", 1), ("max_subnormal", (1 << 52) - 1),
        ("min_normal", 1 << 52), ("one", 0x3ff0000000000000),
        ("max_finite", 0x7fefffffffffffff),
        ("positive_infinity", 0x7ff0000000000000),
        ("negative_infinity", 0xfff0000000000000),
    ]:
        cases.append(dict(id=name, operation="transport", input=str(value), bits=f"{value:016x}"))
    for value in [0, 1, -1, 2**53 - 1, 2**53, 2**53 + 1, 2**53 + 2,
                  2**53 + 3, -(2**53 + 1), 2**63 - 1, -(2**63)]:
        cases.append(dict(id=f"int64_{value}", operation="int64_to_double", input=str(value), bits=f"{bits(float(value)):016x}"))
    a, b, c = Fraction(1) + Fraction(1, 2**27), Fraction(1) - Fraction(1, 2**27), Fraction(-1)
    rounded_product = Fraction.from_float(float(a * b))
    separate, fused = bits(float(rounded_product + c)), bits(float(a * b + c))
    assert separate == 0 and fused != separate
    cases.append(dict(id="separate_mul_add", operation="mul_add", inputs=[f"{bits(float(x)):016x}" for x in (a,b,c)], bits=f"{separate:016x}", fused_bits=f"{fused:016x}"))
    lines = ["// Generated by tools/generate_oracles.py; do not edit.", '///|', 'test "ci bit patterns" {']
    for case in cases:
        if case['operation'] == 'transport':
            expr = f"({case['input']}UL).reinterpret_as_double()"
        elif case['operation'] == 'int64_to_double':
            expr = f"({case['input']}L).to_double()"
        else:
            # Constant operands are folded by optimizing C compilers before
            # -ffp-contract applies, hiding contraction in release builds. XOR
            # each operand with a mask derived from the process argument count,
            # which no compiler can see; it is zero for any real argument list.
            lines.extend(['  let runtime_mask = (@env.args().length() >> 30).to_uint64()',
                          '  assert_eq(runtime_mask, 0UL)',
                          *[f'  let {n} = (0x{v}UL ^ runtime_mask).reinterpret_as_double()' for n, v in zip('abc', case['inputs'])],
                          '  let product = a * b'])
            expr = "product + c"
        lines.extend([f"  let value = ({expr}).reinterpret_as_uint64()", f"  assert_eq(value, 0x{case['bits']}UL)",
                      '  let hex = value.to_string(radix=16)', '  let padded = "0".repeat(16 - hex.length()) + hex',
                      f'  println("LUNA_BITS {case["id"]} " + padded)'])
    lines.append('}')
    return {ROOT/'testdata/oracles.json': json.dumps(dict(format="binary64", rounding="nearest_ties_even", cases=cases), indent=2)+'\n',
            ROOT/'testdata/expected.bits': ''.join(f"LUNA_BITS {case['id']} {case['bits']}\n" for case in cases),
            ROOT/'src/ci_probe/oracles_wbtest.mbt': subprocess.run(['moonfmt', '-'], input='\n'.join(lines)+'\n', text=True, capture_output=True, check=True).stdout}

def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args=parser.parse_args()
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"stale oracle: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True); path.write_text(content)

if __name__ == '__main__': main()
